scripts_dir:     /g/data3/gx8/extras/vlad/synced/HGT-ID/src
snake_src_dir:   /g/data3/gx8/extras/vlad/synced/HGT-ID/snake_src
human_fa:        /g/data/gx8/extras/vlad/synced/umccr/genomes/hg38/hg38.fa
human_bwa:       /g/data/gx8/extras/vlad/synced/umccr/genomes/hg38/bwa/hg38
virus_fa:        /g/data/gx8/extras/vlad/synced/umccr/genomes/viral/gdc-viral.fa
virus_bwa:       /g/data/gx8/extras/vlad/synced/umccr/genomes/viral/gdc-viral.fa
virus_human_fa:  /g/data/gx8/extras/vlad/synced/umccr/genomes/hg38/viral/hg38_noalt_plus_gdc_viral.fa
virus_human_bwa: /g/data/gx8/extras/vlad/synced/umccr/genomes/hg38/viral/hg38_noalt_plus_gdc_viral
ref_flat:        /g/data/gx8/extras/vlad/synced/umccr/genomes/hg38/viral/HGT_ID/hg38_refFlat.txt.gz
human_cytoband:  /g/data/gx8/extras/vlad/synced/umccr/genomes/hg38/viral/HGT_ID/hg38_cytoBand.txt.gz

threads: 4
sequence_complexity: 0.7  # lowering this number will give more HGT events
virus_read_support: 5

# Integration site parameters
min_pr: 1
min_soft: 5

bam: /g/data/gx8/projects/Saveliev_Viral/SBJ00322/SBJ00322_tumor.bam
output_dir: 'output'
